using System.Globalization;
using System.Text.Json;

namespace EasyGet.Services.Cookies;

public sealed record BrowserCookie(
    string Domain,
    string Path,
    string Name,
    string Value,
    bool Secure,
    long ExpiresUnix);

public static class CookieFileSerializer
{
    private static readonly string[] LineSeparators = ["\r\n", "\n"];

    internal static bool HasExplicitDomainRows(string content)
    {
        ArgumentNullException.ThrowIfNull(content);
        var trimmed = content.Trim();
        if (trimmed.Length == 0)
            return false;

        if (LooksLikeNetscapeCookieFile(trimmed))
        {
            return trimmed
                .Split(LineSeparators, StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries)
                .Any(line =>
                {
                    var fields = line.Split('\t');
                    return fields.Length >= 7
                           && !string.IsNullOrWhiteSpace(
                               fields[0].Replace("#HttpOnly_", "", StringComparison.Ordinal));
                });
        }

        if (!trimmed.StartsWith("[", StringComparison.Ordinal)
            && !trimmed.StartsWith("{", StringComparison.Ordinal))
        {
            return false;
        }

        try
        {
            using var document = JsonDocument.Parse(trimmed);
            return EnumerateCookieJsonItems(document.RootElement)
                .Any(item => !string.IsNullOrWhiteSpace(GetCookieDomain(item, out _)));
        }
        catch (JsonException)
        {
            return false;
        }
    }

    public static IReadOnlyList<string> BuildScopedLines(
        string content,
        MediaPlatformDefinition platform,
        string targetHost)
    {
        ArgumentNullException.ThrowIfNull(content);
        ArgumentNullException.ThrowIfNull(platform);
        ArgumentException.ThrowIfNullOrWhiteSpace(targetHost);

        var lines = CreateHeader();
        var trimmed = content.Trim();
        if (trimmed.Length == 0)
            return lines;

        if (LooksLikeNetscapeCookieFile(trimmed))
        {
            AddNetscapeCookies(trimmed, platform, lines);
            return lines;
        }

        if (trimmed.StartsWith("[", StringComparison.Ordinal)
            || trimmed.StartsWith("{", StringComparison.Ordinal))
        {
            try
            {
                AddJsonCookies(trimmed, platform, lines);
                return lines;
            }
            catch (JsonException)
            {
                // Some browser extensions wrap a raw Cookie header in non-JSON text.
            }
        }

        AddPlainTextCookies(trimmed, platform, targetHost, lines);
        return lines;
    }

    public static IReadOnlyList<string> BuildScopedLines(
        IReadOnlyList<BrowserCookie> cookies,
        MediaPlatformDefinition platform)
    {
        ArgumentNullException.ThrowIfNull(cookies);
        ArgumentNullException.ThrowIfNull(platform);

        var lines = CreateHeader();
        foreach (var cookie in cookies)
        {
            if (!IsAllowedDomain(cookie.Domain, platform)
                || !HasSafeFields(cookie.Domain, cookie.Path, cookie.Name, cookie.Value))
            {
                continue;
            }

            var domain = cookie.Domain.Trim();
            var includeSubdomains = domain.StartsWith(".", StringComparison.Ordinal) ? "TRUE" : "FALSE";
            var path = string.IsNullOrWhiteSpace(cookie.Path) ? "/" : cookie.Path;
            var secure = cookie.Secure || cookie.Name.StartsWith("__Secure-", StringComparison.OrdinalIgnoreCase);
            lines.Add(BuildRow(
                domain,
                includeSubdomains,
                path,
                secure,
                Math.Max(0, cookie.ExpiresUnix),
                cookie.Name,
                cookie.Value));
        }

        return lines;
    }

    private static List<string> CreateHeader()
        =>
        [
            "# Netscape HTTP Cookie File",
            "# Generated by EasyGet",
            ""
        ];

    private static void AddNetscapeCookies(
        string content,
        MediaPlatformDefinition platform,
        List<string> lines)
    {
        foreach (var rawLine in content.Split(
                     LineSeparators,
                     StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries))
        {
            var fields = rawLine.Split('\t');
            var isHttpOnly = rawLine.StartsWith("#HttpOnly_", StringComparison.Ordinal);
            if (rawLine.StartsWith('#') && !isHttpOnly)
                continue;
            if (fields.Length < 7)
                continue;

            var domain = isHttpOnly
                ? fields[0]["#HttpOnly_".Length..]
                : fields[0];
            if (IsAllowedDomain(domain, platform) && HasSafeFields(fields))
                lines.Add(rawLine);
        }
    }

    private static void AddJsonCookies(
        string content,
        MediaPlatformDefinition platform,
        List<string> lines)
    {
        using var document = JsonDocument.Parse(content);
        foreach (var item in EnumerateCookieJsonItems(document.RootElement))
        {
            var domain = GetCookieDomain(item, out var domainImpliesHostOnly);
            var name = GetOptionalString(item, "name");
            var value = GetCookieValue(item);
            var path = GetOptionalString(item, "path");
            if (string.IsNullOrWhiteSpace(path))
                path = "/";

            if (!IsAllowedDomain(domain, platform)
                || string.IsNullOrWhiteSpace(name)
                || !HasSafeFields(domain, path, name, value))
            {
                continue;
            }

            var hostOnly = GetOptionalBoolean(item, "hostOnly") || domainImpliesHostOnly;
            var secure = GetOptionalBoolean(item, "secure")
                         || name.StartsWith("__Secure-", StringComparison.OrdinalIgnoreCase);
            lines.Add(BuildRow(
                domain,
                hostOnly ? "FALSE" : "TRUE",
                path,
                secure,
                GetCookieExpiry(item),
                name,
                value));
        }
    }

    private static void AddPlainTextCookies(
        string content,
        MediaPlatformDefinition platform,
        string targetHost,
        List<string> lines)
    {
        var cookieDomain = ResolvePlainTextDomain(platform, targetHost);
        if (cookieDomain.Length == 0)
            return;

        var headerValue = ExtractCookieHeaderValue(content);
        foreach (var pair in headerValue.Split(';', StringSplitOptions.RemoveEmptyEntries))
        {
            var separatorIndex = pair.IndexOf('=');
            if (separatorIndex <= 0)
                continue;

            var name = pair[..separatorIndex].Trim();
            var value = pair[(separatorIndex + 1)..].Trim();
            if (string.IsNullOrWhiteSpace(name)
                || name.Any(char.IsWhiteSpace)
                || !HasSafeFields(cookieDomain, "/", name, value))
            {
                continue;
            }

            lines.Add(BuildRow(cookieDomain, "TRUE", "/", true, 0, name, value));
        }
    }

    private static string ResolvePlainTextDomain(
        MediaPlatformDefinition platform,
        string targetHost)
    {
        var normalizedHost = targetHost.Trim().TrimStart('.');
        var domain = platform.CookieDomains.FirstOrDefault(candidate =>
                         MediaPlatformResolver.HostMatches(normalizedHost, candidate))
                     ?? platform.CookieDomains.FirstOrDefault();
        if (string.IsNullOrWhiteSpace(domain))
            domain = normalizedHost;
        if (string.IsNullOrWhiteSpace(domain))
            return "";

        return $".{domain.Trim().TrimStart('.')}";
    }

    private static bool IsAllowedDomain(string domain, MediaPlatformDefinition platform)
    {
        var normalizedDomain = domain.Trim();
        if (normalizedDomain.StartsWith("#HttpOnly_", StringComparison.Ordinal))
            normalizedDomain = normalizedDomain["#HttpOnly_".Length..];
        normalizedDomain = normalizedDomain.TrimStart('.');

        return normalizedDomain.Length > 0
               && platform.CookieDomains.Any(allowed =>
                   MediaPlatformResolver.HostMatches(normalizedDomain, allowed));
    }

    private static bool HasSafeFields(params string[] fields)
        => fields.All(field => field is not null
                               && !field.Contains('\t')
                               && !field.Contains('\r')
                               && !field.Contains('\n'));

    private static string BuildRow(
        string domain,
        string includeSubdomains,
        string path,
        bool secure,
        long expiry,
        string name,
        string value)
        => $"{domain}\t{includeSubdomains}\t{path}\t{(secure ? "TRUE" : "FALSE")}\t{expiry}\t{name}\t{value}";

    private static IEnumerable<JsonElement> EnumerateCookieJsonItems(JsonElement root)
    {
        if (root.ValueKind == JsonValueKind.Array)
        {
            foreach (var item in root.EnumerateArray())
                yield return item;
            yield break;
        }

        if (root.ValueKind != JsonValueKind.Object)
            yield break;

        foreach (var propertyName in new[] { "cookies", "data" })
        {
            if (!root.TryGetProperty(propertyName, out var cookies)
                || cookies.ValueKind != JsonValueKind.Array)
            {
                continue;
            }

            foreach (var item in cookies.EnumerateArray())
                yield return item;
            yield break;
        }
    }

    private static string GetCookieValue(JsonElement item)
    {
        var value = GetOptionalString(item, "value");
        return value.Length > 0 ? value : GetOptionalString(item, "sessionValue");
    }

    private static string GetCookieDomain(JsonElement item, out bool domainImpliesHostOnly)
    {
        domainImpliesHostOnly = false;
        var domain = GetOptionalString(item, "domain").Trim();
        if (domain.Length > 0)
            return domain;

        var host = GetOptionalString(item, "host").Trim();
        if (host.Length > 0)
        {
            domainImpliesHostOnly = !host.StartsWith(".", StringComparison.Ordinal);
            return host;
        }

        var url = GetOptionalString(item, "url").Trim();
        if (Uri.TryCreate(url, UriKind.Absolute, out var uri) && uri.Host.Length > 0)
        {
            domainImpliesHostOnly = true;
            return uri.Host;
        }

        return "";
    }

    private static long GetCookieExpiry(JsonElement item)
    {
        foreach (var propertyName in new[] { "expirationDate", "expires", "expiry" })
        {
            var expiry = GetOptionalUnixTime(item, propertyName);
            if (expiry > 0)
                return expiry;
        }

        return 0;
    }

    private static string GetOptionalString(JsonElement element, string propertyName)
    {
        if (element.ValueKind != JsonValueKind.Object
            || !element.TryGetProperty(propertyName, out var value))
        {
            return "";
        }

        return value.ValueKind switch
        {
            JsonValueKind.String => value.GetString() ?? "",
            JsonValueKind.Number => value.GetRawText(),
            JsonValueKind.True => "true",
            JsonValueKind.False => "false",
            _ => ""
        };
    }

    private static bool GetOptionalBoolean(JsonElement element, string propertyName)
    {
        if (element.ValueKind != JsonValueKind.Object
            || !element.TryGetProperty(propertyName, out var value))
        {
            return false;
        }

        return value.ValueKind switch
        {
            JsonValueKind.True => true,
            JsonValueKind.False => false,
            JsonValueKind.String => bool.TryParse(value.GetString(), out var parsed) && parsed,
            JsonValueKind.Number => value.TryGetInt32(out var number) && number != 0,
            _ => false
        };
    }

    private static long GetOptionalUnixTime(JsonElement element, string propertyName)
    {
        if (element.ValueKind != JsonValueKind.Object
            || !element.TryGetProperty(propertyName, out var value))
        {
            return 0;
        }

        var seconds = value.ValueKind switch
        {
            JsonValueKind.Number when value.TryGetDouble(out var number) => number,
            JsonValueKind.String when double.TryParse(
                value.GetString(),
                NumberStyles.Float,
                CultureInfo.InvariantCulture,
                out var number) => number,
            _ => 0
        };

        if (!double.IsFinite(seconds) || seconds <= 0)
            return 0;
        if (seconds >= long.MaxValue)
            return long.MaxValue;
        return (long)seconds;
    }

    private static bool LooksLikeNetscapeCookieFile(string content)
    {
        if (content.Contains("# Netscape HTTP Cookie File", StringComparison.OrdinalIgnoreCase))
            return true;

        return content
            .Split(LineSeparators, StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries)
            .Any(line => !line.StartsWith('#') && line.Split('\t').Length >= 7);
    }

    private static string ExtractCookieHeaderValue(string content)
    {
        var contentLines = content.Split(
            LineSeparators,
            StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries);
        var cookieLine = contentLines.FirstOrDefault(line =>
            line.StartsWith("cookie:", StringComparison.OrdinalIgnoreCase));
        var value = cookieLine ?? content.Trim();
        return value.StartsWith("cookie:", StringComparison.OrdinalIgnoreCase)
            ? value["cookie:".Length..].Trim()
            : value;
    }
}
